#!/bin/bash
BUCKET='s3://dev.mvml.net/'
if [ -n "$1" ] && [ $1 == 'production' ]
then
  BUCKET='s3://www.mvml.net/'
fi

COMMAND="aws s3 sync . ${BUCKET}"
FILE_ARGS=(
  "exclude '*'"
  "include '*.html'"
  "exclude 'node_modules/*'"
  "include 'js/*'"
  "include 'css/*'"
  "include 'img/*'"
  "include 'dist/*'"
  "include 'models/*'"
);
for arg in "${FILE_ARGS[@]}"
do
  COMMAND="${COMMAND} --${arg}"
done
COMMAND="${COMMAND} --acl public-read --delete"

echo ${COMMAND}
eval ${COMMAND}

COMMAND="aws s3 sync . ${BUCKET} --exclude '*' --include '*.mvml' --recursive --acl public-read --delete --content-type 'text/plain'"

echo ${COMMAND}
eval ${COMMAND}
