#!/bin/bash
aws s3 sync . s3://dev.mvml.net/ --exclude '*' --include '*.html' --exclude 'node_modules/*' --include 'js/*' --include 'css/*' --include 'img/*' --include 'dist/*' --include 'www/*' --acl public-read --delete
#aws s3 sync . s3://mvml-dev/ --acl public-read --exclude '.git/*' --exclude '.gitignore' --exclude 'upload-to-s3' --exclude 'node_modules/*' --exclude 'gulpfile.js' --exclude 'package.json'
