#! /bin/sh
### BEGIN INIT INFO
# Provides:          mvml-server
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: an mvml server
# Description:       mvml-server, my fun test server for serving mvml
### END INIT INFO

DIR=/home/JScott/mvml/
SCRIPT=server.rb

case "$1" in
	start)
		cd ${DIR}
		sudo ruby ${SCRIPT} &
		;;
	stop)
		sudo pkill -f "ruby ${SCRIPT}"
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
